Sprint5
ClevertecFrontendLab/AdrianDmitruk pull request #3
Opened 2023-03-09 18:33 UTC by AdrianDmitruk

2023-03-09 18:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 85%.
Общее количество тестов: 20.
Количество непройденных тестов: 3.
***
**authorization and registartion -- password recovery -- reset password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/authorization%20and%20registartion%20--%20password%20recovery%20--%20reset%20password%20validation%20(failed).png)
***
**authorization and registartion -- password recovery -- success reset password (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/authorization%20and%20registartion%20--%20password%20recovery%20--%20success%20reset%20password%20(failed).png)
***
**authorization and registartion -- registration -- validation first step (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/authorization%20and%20registartion%20--%20registration%20--%20validation%20first%20step%20(failed).png)
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678387120/server%20error%20authorization.png)

2023-03-09 20:44 UTC, Ivan6813 requested changes

2023-03-09 20:44 UTC, Ivan6813 commented on src/App.jsx
> +import { selectRegistrationData } from './redux/auth/selectors';
верстка поехала, на других скринах тоже есть проблемы с позиционированием этого текста 

![msedge_pQQD8z7zoW](https://user-images.githubusercontent.com/79784960/224148081-a1e52871-fba3-4c1b-af05-d465833616c4.png)

2023-03-09 20:44 UTC, Ivan6813 commented on src/App.jsx
> +          {isAuth ? (
посмотри как можно реализовать приватный роут, вот так ставить условия в роуте не очень хорошая идея

2023-03-09 20:44 UTC, Ivan6813 commented on src/assets/icon/eye/close-eye/index.tsx
> +    </svg>
почему бы просто не импортировать svg  из figma? зачем создавать под каждую иконку файл. Посмотри как импортировать svg и картинки в react

2023-03-09 20:44 UTC, Ivan6813 commented on src/components/blocks/modal/auth-modal/auth-modal.tsx
> +export const AuthModal: FC<AuthModalProps> = ({ showHeader, children }) => (
если типизируешь компонент через FC, то children в interface  можно не писать, они будут и так подтягиваться

2023-03-09 20:44 UTC, Ivan6813 commented on src/components/common/input/input-phone/input-phone.tsx
> +    // setIsFocused(true);
закомментированного кода быть не должно, на 44 строке тоже и в целом в других файлах, повторяться уже не буду

2023-03-09 20:44 UTC, Ivan6813 commented on src/components/common/input/input-phone/input-phone.tsx
> +      setIsPhoneNumberValid(/^\+375\s\((29|33|25|44)\)\s\d{3}-\d{2}-\d{2}$/.test(phoneNumber));
+375\s\((29|33|25|44)\)\s\d{3}-\d{2}-\d{2} повторяется на 22 строке, есть смысл вынести это в константу, дать ей понятное имя и переиспользовать

2023-03-09 20:44 UTC, Ivan6813 commented on src/components/common/input/input-phone/input-phone.tsx
> +          ['+', '3', '7', '5', ' ', '(', /\d/, /\d/, ')', ' ', /\d/, /\d/, /\d/, '-', /\d/, /\d/, '-', /\d/, /\d/]
тоже можно в константу вынести и убрать закомментированный код

2023-03-10 13:03 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 70%.
Общее количество тестов: 16.
Количество непройденных тестов: 2.

2023-03-10 13:08 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 90%.
Общее количество тестов: 20.
Количество непройденных тестов: 2.
***
**authorization and registartion -- password recovery -- reset password validation (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/authorization%20and%20registartion%20--%20password%20recovery%20--%20reset%20password%20validation%20(failed).png)
***
**authorization and registartion -- registration -- validation first step (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/authorization%20and%20registartion%20--%20registration%20--%20validation%20first%20step%20(failed).png)
***
**error reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/error%20reset%20password.png)
***
**first enter.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/first%20enter.png)
***
**incorrect logit or password error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/incorrect%20logit%20or%20password%20error.png)
***
**loader authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/loader%20authorization.png)
***
**password hidden.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/password%20hidden.png)
***
**password shown.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/password%20shown.png)
***
**recovery page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/recovery%20page.png)
***
**registration already used error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration%20already%20used%20error.png)
***
**registration error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration%20error.png)
***
**registration page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration%20page.png)
***
**registration-first-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration-first-step.png)
***
**registration-second-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration-second-step.png)
***
**registration-success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration-success.png)
***
**registration-third-step.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/registration-third-step.png)
***
**send email error.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/send%20email%20error.png)
***
**send email success.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/send%20email%20success.png)
***
**server error authorization.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/server%20error%20authorization.png)
***
**success reset password.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1678453738/success%20reset%20password.png)

2023-03-10 13:13 UTC, Ivan6813 approved these changes

2023-03-10 13:13 UTC, Ivan6813 commented on src/components/blocks/modal/auth-modal/auth-modal.tsx
> +// в данном случаи это не так. ничего не подтягивается'
отвечать можно в гитхабе просто) не надо писать так комментарии в коде)

2023-03-10 13:19 UTC, merged

2023-03-10 13:19 UTC, AdrianDmitruk commented on src/components/blocks/modal/auth-modal/auth-modal.tsx
> +// в данном случаи это не так. ничего не подтягивается'
)))