Sprint7
ClevertecFrontendLab/AdrianDmitruk pull request #5
Opened 2023-03-26 00:32 UTC by AdrianDmitruk

2023-03-26 00:46 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679791581/9-app%20-burger-menu-close-768px.png)

2023-03-26 08:40 UTC, Ivan6813 requested changes

2023-03-26 08:40 UTC, Ivan6813 commented on src/App.jsx
>              <Route path='/contract' element={<TermsPage contentView='contract' />} />
текст в хлебных крошках не так должен переносится, посмотри как в макете

![msedge_2yMKR5PHRl](https://user-images.githubusercontent.com/79784960/227763199-8ca783ba-ca07-4de7-96c7-5625e1005233.png)

2023-03-26 08:40 UTC, Ivan6813 commented on src/App.jsx
>            <Route path='/books/:category/:id' element={<BookPage />} />
такие карточки должны иметь прозрачность и blur, сверься с макетом

![msedge_G8SAitF0Va](https://user-images.githubusercontent.com/79784960/227763237-80aaf2bf-4288-4f0d-a846-91b7bfe05d45.png)

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/blocks/full-book/profile-book/profile-book.tsx
> +      await dispatch(fetchFullBook(idPage));
а зачем здесь писать async await? делай это в саге или санке в зависимости что ты используешь

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/common/card-block/card-block.tsx
>        const res = await dispatch(fetchAddBooking(params));
вешай await там, где ты обрабатываешь экшен, а не перед dispatch

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/common/card-block/card-block.tsx
> +  const light = useCallback((string: string) => <Hightlight str={string} filter={filter ?? ''} />, [filter]);
зачем useCallback если ты эту функцию не передаешь пропсом, а вызываешь в этом же компоненте?

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/common/form-field/form-field.tsx
> +        {error === 'Поле не может быть пустым' && showEmptyField && (
текста ошибок вынеси в константы, создай объект и в него запихни все значения ошибок

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/common/form-field/form-field.tsx
> +                    error === ' цифрой ' ||
у тебя одно и тоже условие повторяется три раза, вынеси его наверх компонента в константу и потом переиспользуй

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/common/notification-booking/notification-booking.tsx
> +  if (statusEditComment === 'ok') {
статусы тоже в один объект в файл с константами нужно вынести

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/header/header.tsx
> +            <img className={styles.headerUserAvatar} src={`${HOST_ENDPOINT}${user.avatar}`} alt='Avatar' />
`<img className={styles.headerUserAvatar} src={ user?.avatar ? '${HOST_ENDPOINT}${user.avatar}' : Avatar } alt='Avatar' />`

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/layouts/layout-main-page/layout-main-page.tsx
> +    return () => window.removeEventListener('resize', handleResize);
этот костыль повторяется, создай кастомный хук для него и переиспользуй

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/navigate/navigate.tsx
> +      onClick();
onClick очень странное название для функции, название функции должно отражать то, что эта функцию делает

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/navigate/navigate.tsx
> +            onClick={() => handleClick()}
`onClick={ handleClick }`

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/profile/profile-booking/profile-booking.tsx
> +          <img className={styles.cardImgList} src={`${HOST_ENDPOINT}${items.book.image}`} alt='book' />
здесь тоже перенеси тернарник в атрибут src. В целом все замечания применимы ко всему коду, а не конкретному месту, что бы не писать одинаковые комментарии

2023-03-26 08:40 UTC, Ivan6813 commented on src/components/profile/profile-info/profile-info.tsx
> +    .matches(/^\S+@\S+\.\S+$/, 'Введите корректный e-mail'),
регулярки тоже выноси в константы и дай им понятное название

2023-03-26 08:40 UTC, Ivan6813 commented on src/pages/profile/profile-page.tsx
> +      <BookingModal isOpen={isModalOpen} onClose={handleCloseModal} title='Оцените книгу' isRate={true}>
вынеси модалку в отдельный компонент и все что нужно прокинь пропсами

2023-03-26 09:37 UTC, Ivan6813 requested changes

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +export interface User {
в личном кабинете по умолчанию поля недоступны для редактирования, после нажатия на кнопку редактировать и выбрать поле пароль, ничего не вводить в него и убрать с него фокус, то появляется ошибка - это ок. Но если снова нажать на кнопку редактировать, то поля становятся недоступными для редактирования, а ошибка в поле пароль продолжает висеть. Нужно сбрасывать ошибки, если поля становятся недоступными для редактирования

![chrome_4fsu3Smdup](https://user-images.githubusercontent.com/79784960/227766723-24bf1da7-b8dc-4ce7-8666-5b51003b1ed8.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  username: string;
иконка в кнопке сортировка по рейтингу не такая как на макете, посмотри как должны выглядеть иконка со стрелкой вверх

![chrome_7HO8HWbHz5](https://user-images.githubusercontent.com/79784960/227766816-f723c694-de8e-4374-9cda-98735e96f2c8.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  confirmed: boolean;
на планшете если в поиске нашлась одна карточка, то она расположена по центру, нужно прижать её к левому краю

![chrome_cBJlGoHqsG](https://user-images.githubusercontent.com/79784960/227766874-c3104739-f385-472f-a864-5dcac1a4080e.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  createdAt: Date;
поменяй местами стрелку в положении развернутых и свернутых комментариев, если стрелка вниз, то комменты свернуты, а у тебя наоборот

![chrome_Dc57rVqj4E](https://user-images.githubusercontent.com/79784960/227766954-822cd6be-d55b-4aa6-b9a2-e15e435cf8b7.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  firstName: string;
не подсвечивается Витрина книг, она раскрылась, но активная подсветка осталась на прошлом пункте

![chrome_gEceN0ZjwP](https://user-images.githubusercontent.com/79784960/227767066-f73e881c-0c56-408d-bec0-91e500fc319e.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  phone: string;
при ошибке неверного логина или пароль не дизейблится кнопка Вход, можно щелкать по ней и отправлять ненужные запросы

![chrome_Kwnge0B36f](https://user-images.githubusercontent.com/79784960/227767147-d39264f4-d344-4166-9854-67c8aeeecc34.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  comments: CommentsUser | null;
какой-то большой отступ

![chrome_N8OvzXhUhP](https://user-images.githubusercontent.com/79784960/227767166-022ff16f-9fac-49ac-a9e9-ed1e9b45ae2f.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  avatar: string | null;
текст в footer переноситься не так как в макете

![chrome_oxYjWFoVC8](https://user-images.githubusercontent.com/79784960/227767200-0189d2e6-bd63-47b8-a488-5d8de18c88b3.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  booking: BookingUser | null;
что-то не так с отображением картинки на планшете

![chrome_rdlCeCgI76](https://user-images.githubusercontent.com/79784960/227767258-73075bd4-5bb4-4474-9399-bf2047663e03.png)

2023-03-26 09:37 UTC, Ivan6813 commented on src/redux/user/types.ts
> +  history: HistoryUser | null;
прижми даты к левому краю в мобилке, а то они разбросаны

![chrome_X4oof1M1yd](https://user-images.githubusercontent.com/79784960/227767311-3eb9c904-2500-44de-9623-522144657541.png)

2023-03-26 23:17 UTC, AdrianDmitruk commented on src/components/common/form-field/form-field.tsx
> +                    error === ' цифрой ' ||
Не совсем конечно три одинаковых)

2023-03-26 23:20 UTC, ValadzkoAliaksei commented on src/App.jsx
> +          <Route path='/profile' element={<ProfilePage />} />
все строки роутов вынести в константу

2023-03-26 23:20 UTC, ValadzkoAliaksei commented on src/components/common/cover/cover.tsx
> +interface CoverProps {
все интерфейсы в типы

2023-03-26 23:20 UTC, ValadzkoAliaksei commented on src/components/common/notification-booking/notification-booking.tsx
> +  }
вообще круто, если сможешь сделать 1 компонент выпадашки на весь проект. И что бы он  зависел от 1 переменной

2023-03-26 23:20 UTC, ValadzkoAliaksei commented on src/components/profile/profile-info/profile-info.tsx
> +      const digits = /^(?=.*\d).*$/.test(value ?? '');
все регулярки вынести в отдельный файл

2023-03-26 23:27 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679873223/9-app%20-burger-menu-close-768px.png)

2023-03-27 00:17 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 98%.
Общее количество тестов: 98.
Количество непройденных тестов: 1.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- history-tests -- update-review -- fail (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679876270/Sprint%207%20--%20Profile%20functions%20tests%20--%20history-tests%20--%20update-review%20--%20fail%20(failed).png)

2023-03-27 00:37 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/24-1440-profile-empty-card.png)
***
**25-1440-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/25-1440-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/AdrianDmitruk/1679877452/9-app%20-burger-menu-close-768px.png)

2023-03-27 06:17 UTC, Ivan6813 approved these changes

2023-03-27 09:26 UTC, ValadzkoAliaksei approved these changes

2023-03-27 09:27 UTC, merged